### PR TITLE
Update PackageConfig to fix running on linux

### PR DESCRIPTION
**Pull request by cszatma**
* Update the `PackageConfig` dependency to fix running on linux (see [here](https://github.com/shibapm/PackageConfig/pull/7) for more details)
* Change repo name to `shibapm/Komondor` in docs

### CODE REVIEW

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
You're welcome to ship a release ( all it requires is shipping the tag I think)

**Comment by cszatma** [comment]
I need write access to the repo to be able to do that. If you can give that to me I'll release a new version. Also do you use [rocket](https://github.com/shibapm/Rocket) to release it? That tool looks cool because it hides the dev deps.

**Comment by orta** [comment]
You are a member of the org - you should have a access? And yeah, I believe so - the "massive" deploy docs are here: https://github.com/shibapm/Komondor#deployment

**Comment by cszatma** [comment]
I think you still need to configure access for members on a per repo basis. It's under Settings > Collaborators & teams

**Comment by cszatma** [comment]
I believe this is because I am an organization member instead of owner, so I need to be given explicit write permission to repos in the organization.

**Comment by cszatma** [comment]
@orta I still don't have write access. Would you be able to give it to me?

**Pull request merged**
